### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by raygerrard** [blakeembrey/atom-dash#12]
[Enter steps to reproduce below:]

1. ...CMD + Shift + p
2. ... Dash: shortcut

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [dash](https://github.com/blakeembrey/atom-dash) package, v1.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelection' of undefined

```
At /Users/raygerrard/.atom/packages/dash/lib/dash.coffee:16

TypeError: Cannot read property 'getSelection' of undefined
  at atom-workspace.module.exports.shortcut (/Users/raygerrard/.atom/packages/dash/lib/dash.coffee:16:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:35.6 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
  4x -0:32.8 core:backspace (atom-text-editor.editor.mini)
     -0:31.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:31.9 core:cancel (atom-text-editor.editor.mini)
     -0:06.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:00.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 dash:shortcut (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
dash, v1.0.2

# Dev
No dev packages
```

**Comment by blakeembrey** [comment]
@raygerrard Fixed and released in `v1.0.3`.
